### ISSUE TITLE
'for' won't iterate unitl stdout is closed in Python2

### ISSUE THREAD

**Issue by ayuanx** [philchristensen/svn-color#4]
In Python2, the following loop blocks until subprocess is ended.
 
> for line in task.stdout:

Should use old fashioned while + readline to process realtime output.

>        while True:
>            line = task.stdout.readline()
>            if not line:
>                break
>            sys.stdout.write(colorize(line))
>            sys.stdout.flush()

If the output is short, this isn't an issue; but if the output is very long, you won't be able to see realtime output until subproecess terminates.

**Comment by philchristensen** [comment]
If you submit a PR I'll merge it immediately. I haven't really worked on this script in ages.

**Comment by ayuanx** [comment]
Done.
